### ISSUE TITLE
Not Checking if Random String already exists in DB.

### ISSUE THREAD

**Issue by SrikanthYashaswi** [aligoren/ts-url-shortener#1]
https://github.com/aligoren/ts-url-shortener/blob/eee85262a85994c9888fec365921bee56b6f88b8/src/controllers/shortener/shortener.controller.ts#L67-L80

If the function generates a random string already existing in DB, the previously referenced link to that random string will be gone.

**Comment by aligoren** [comment]
Yes, right. Maybe you can open a new PR? :) pull requests are welcome :)

**Comment by SrikanthYashaswi** [comment]
yup surely will do

**Comment by aligoren** [comment]
I'm happy with your contrubition. Thanks :) I'm waiting.

**Comment by SrikanthYashaswi** [comment]
Throwing this error while config,
Error: querySrv ENOTFOUND _mongodb._tcp.127.0.0.1

what value to provide in .env file for MONGO_PATH

**Comment by aligoren** [comment]
MONGO_PATH must be a Mongo Address. You should use Mongo Cloud for demo purposes.

**Comment by SrikanthYashaswi** [comment]
i have submitted a pull request

**Comment by aligoren** [comment]
I merged :)
